cart.settings:
  type: config_object
  label: 'Cart settings'
  mapping:
    enabled:
      type: boolean
      label: 'Module enabled'
    cart_expiry:
      type: integer
      label: 'Cart expiry (in seconds)'
    # Add more configuration options here as needed.
