name: ddev-dream-hotel
networks:
    ddev_default:
        external: true
        name: ddev_default
    default:
        name: ddev-dream-hotel_default
services:
    db:
        build:
            args:
                BASE_IMAGE: drud/ddev-dbserver-mariadb-10.4:v1.21.5
                gid: "20"
                uid: "501"
                username: mac
            context: /Users/mac/projects/dream-hotel/.ddev/.dbimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_NICE
        command: []
        container_name: ddev-dream-hotel-db
        environment:
            COLUMNS: "186"
            DDEV_DATABASE: mariadb:10.4
            DDEV_HOSTNAME: dream-hotel.ddev.site
            DDEV_PHP_VERSION: "8.0"
            DDEV_PRIMARY_URL: http://dream-hotel.ddev.site
            DDEV_PROJECT: dream-hotel
            DDEV_PROJECT_TYPE: drupal9
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: dream-hotel
            DDEV_TLD: ddev.site
            DOCKER_IP: 127.0.0.1
            GOARCH: arm64
            GOOS: darwin
            HOST_DOCKER_INTERNAL_IP: ""
            IS_DDEV_PROJECT: "true"
            LINES: "44"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/dream-hotel-db/mysql_history
            MYSQL_PWD: db
            PGDATABASE: db
            PGHOST: 127.0.0.1
            PGPASSWORD: db
            PGUSER: db
            POSTGRES_DB: db
            POSTGRES_PASSWORD: db
            POSTGRES_USER: db
            TZ: ""
            USER: mac
        healthcheck:
            interval: 1s
            retries: 120
            start_period: 2m0s
            timeout: 2m0s
        hostname: dream-hotel-db
        image: drud/ddev-dbserver-mariadb-10.4:v1.21.5-dream-hotel-built
        labels:
            com.ddev.app-type: drupal9
            com.ddev.approot: /Users/mac/projects/dream-hotel
            com.ddev.platform: ddev
            com.ddev.site-name: dream-hotel
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              published: "61701"
              target: 3306
        restart: "no"
        stop_grace_period: 1m0s
        user: "501:20"
        volumes:
            - source: database
              target: /var/lib/mysql
              type: volume
              volume:
                nocopy: true
            - bind:
                create_host_path: true
              source: /Users/mac/projects/dream-hotel/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              source: /Users/mac/projects/dream-hotel/.ddev/db_snapshots
              target: /mnt/snapshots
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
        working_dir: /home/mac
    dba:
        container_name: ddev-dream-hotel-dba
        environment:
            HTTP_EXPOSE: 8036:80
            HTTPS_EXPOSE: 8037:80
            PMA_PASSWORD: root
            PMA_USER: root
            TZ: ""
            UPLOAD_LIMIT: 1024M
            VIRTUAL_HOST: dream-hotel.ddev.site
        expose:
            - "80"
        healthcheck:
            interval: 2m0s
            retries: 1
            timeout: 2s
        hostname: dream-hotel-dba
        image: phpmyadmin:5
        labels:
            com.ddev.app-type: drupal9
            com.ddev.approot: /Users/mac/projects/dream-hotel
            com.ddev.platform: ddev
            com.ddev.site-name: dream-hotel
        networks:
            ddev_default: null
            default: null
        restart: "no"
        working_dir: /root
    web:
        build:
            args:
                BASE_IMAGE: drud/ddev-webserver:v1.21.5
                DDEV_PHP_VERSION: "8.0"
                gid: "20"
                uid: "501"
                username: mac
            context: /Users/mac/projects/dream-hotel/.ddev/.webimageBuild
            dockerfile: Dockerfile
        cap_add:
            - SYS_PTRACE
        container_name: ddev-dream-hotel-web
        environment:
            COLUMNS: "186"
            DDEV_COMPOSER_ROOT: /var/www/html
            DDEV_DATABASE: mariadb:10.4
            DDEV_DOCROOT: web
            DDEV_FILES_DIR: /var/www/html/web/sites/default/files
            DDEV_HOSTNAME: dream-hotel.ddev.site
            DDEV_MUTAGEN_ENABLED: "false"
            DDEV_PHP_VERSION: "8.0"
            DDEV_PRIMARY_URL: http://dream-hotel.ddev.site
            DDEV_PROJECT: dream-hotel
            DDEV_PROJECT_TYPE: drupal9
            DDEV_ROUTER_HTTP_PORT: "80"
            DDEV_ROUTER_HTTPS_PORT: "443"
            DDEV_SITENAME: dream-hotel
            DDEV_TLD: ddev.site
            DDEV_VERSION: v1.21.6
            DDEV_WEBSERVER_TYPE: nginx-fpm
            DDEV_XDEBUG_ENABLED: "false"
            DEPLOY_NAME: local
            DOCKER_IP: 127.0.0.1
            DOCROOT: web
            DRUSH_ALLOW_XDEBUG: "1"
            DRUSH_OPTIONS_URI: http://dream-hotel.ddev.site
            GOARCH: arm64
            GOOS: darwin
            HOST_DOCKER_INTERNAL_IP: ""
            HTTP_EXPOSE: 80:80,8025:8025
            HTTPS_EXPOSE: 443:80,8026:8025
            IS_DDEV_PROJECT: "true"
            LINES: "44"
            MYSQL_HISTFILE: /mnt/ddev-global-cache/mysqlhistory/dream-hotel-web/mysql_history
            MYSQL_PWD: db
            NODE_EXTRA_CA_CERTS: /mnt/ddev-global-cache/mkcert/rootCA.pem
            PGDATABASE: db
            PGHOST: db
            PGPASSWORD: db
            PGUSER: db
            PHP_IDE_CONFIG: serverName=dream-hotel.ddev.site
            SSH_AUTH_SOCK: /home/.ssh-agent/socket
            TZ: ""
            USER: mac
            VIRTUAL_HOST: dream-hotel.ddev.site
            npm_config_cache: /mnt/ddev-global-cache/npm
        external_links:
            - ddev-router:dream-hotel.ddev.site
        healthcheck:
            interval: 1s
            retries: 120
            start_period: 2m0s
            timeout: 2m0s
        hostname: dream-hotel-web
        image: drud/ddev-webserver:v1.21.5-dream-hotel-built
        labels:
            com.ddev.app-type: drupal9
            com.ddev.approot: /Users/mac/projects/dream-hotel
            com.ddev.platform: ddev
            com.ddev.site-name: dream-hotel
        networks:
            ddev_default: null
            default: null
        ports:
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 80
            - host_ip: 127.0.0.1
              mode: ingress
              protocol: tcp
              target: 443
        restart: "no"
        user: "501:20"
        volumes:
            - consistency: cached
              source: ../
              target: /var/www/html
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /Users/mac/projects/dream-hotel/.ddev
              target: /mnt/ddev_config
              type: bind
            - bind:
                create_host_path: true
              read_only: true
              source: /Users/mac/projects/dream-hotel/.ddev/xhprof
              target: /usr/local/bin/xhprof
              type: bind
            - source: ddev-global-cache
              target: /mnt/ddev-global-cache
              type: volume
              volume: {}
            - source: ddev-ssh-agent_socket_dir
              target: /home/.ssh-agent
              type: volume
              volume: {}
        working_dir: /var/www/html/
volumes:
    database:
        external: true
        name: dream-hotel-mariadb
    ddev-global-cache:
        external: true
        name: ddev-global-cache
    ddev-ssh-agent_socket_dir:
        external: true
        name: ddev-ssh-agent_socket_dir

